apiVersion: apps/v1
kind: Deployment
metadata:
  name: istone-frontend
  labels:
    app: istone-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: istone-frontend
  template:
    metadata:
      labels:
        app: istone-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources: {{ toYaml .Values.resources | nindent 12 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istone-backend
  labels:
    app: istone-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: istone-backend
  template:
    metadata:
      labels:
        app: istone-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources: {{ toYaml .Values.resources | nindent 12 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: istone-mysql
  labels:
    app: istone-mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: istone-mysql
  template:
    metadata:
      labels:
        app: istone-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.userPassword }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
