apiVersion: v1
kind: Service
metadata:
  name: istone-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
  selector:
    app: istone-frontend

---

apiVersion: v1
kind: Service
metadata:
  name: istone-backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
  selector:
    app: istone-backend

---

apiVersion: v1
kind: Service
metadata:
  name: istone-mysql
spec:
  type: {{ .Values.service.mysql.type }}
  ports:
    - port: {{ .Values.service.mysql.port }}
  selector:
    app: istone-mysql
